#site settings
title: "Mageluer's Blog"
author: Mageluer
email: kissongg@gmail.com
description: "海贼王"

#Serving
baseurl: /jekyll_demo
url: "http://mageluer.github.io"

#Outputting

#Pagination
paginate: 5

gems:
  [jekyll-paginate]
